# Flutter release keep rules
-keep class io.flutter.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-keep class io.flutter.embedding.** { *; }
-keep class io.flutter.embedding.engine.** { *; }
-keep class io.flutter.embedding.engine.plugins.** { *; }
-keep class io.flutter.embedding.engine.plugins.shim.** { *; }
-keep class io.flutter.plugin.editing.** { *; }
-keep class io.flutter.plugin.platform.** { *; }
# Keep classes generated by the Flutter tool
-keep class dev.edwardiaz.pixel_tictactoe.** { *; }

# Flutter's deferred-components support references Play Core classes that are
# not shipped in a sideloaded APK.
-dontwarn com.google.android.play.core.**
